<?php
/**
 * Studioforty9_Recaptcha
 *
 * @category  Studioforty9
 * @package   Studioforty9_Recaptcha
 * @author    StudioForty9 <info@studioforty9.com>
 * @copyright 2015 StudioForty9 (http://www.studioforty9.com)
 * @license   https://github.com/studioforty9/recaptcha/blob/master/LICENCE BSD
 * @version   1.5.7
 * @link      https://github.com/studioforty9/recaptcha
 * @see       Studioforty9_Recaptcha_Block_Explicit
 */
?>
<div id="recaptcha">
        <?php include 'explicit.phtml' ?>
</div>
<script type="text/javascript">
        $$('<?php echo $this->getAppendToParent(); ?>')[0].appendChild(
                $$('#recaptcha')[0]
        );
</script>
